{%set name = "agate-excel" %}
{%set version = "0.2.1" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "c7621051307a4650b95309a2e13f5774d08719421c9d965b461629a002d048b4" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - agate >=1.5.0
    - openpyxl >=2.3.0
    - xlrd >=0.9.4


test:
  imports:
    - agateexcel

about:
  home: http://agate-excel.readthedocs.org/
  license: MIT
  license_family: MIT
  # license_file: COPYING - not included in MANIFEST - see https://github.com/wireservice/agate-excel/pull/20
  summary: 'agate-excel adds read support for Excel files (xls and xlsx) to agate.'
  doc_url: http://agate-excel.readthedocs.org/
  dev_url: https://github.com/wireservice/agate-excel

extra:
  recipe-maintainers:
    - pmlandwehr
