travis:
  secure:
    BINSTAR_TOKEN: kSO8XpOAckZwjkPi6tUBq2JZXA8RSxSRc+PcloqyTRPp2IkZvLJiOY9uYWbIgpE894zohyb/wBe0nC76ATSe5OqCym/Fx1dEKT7xQNUjWQcQmjnynQ73bpWdCwIkczfuCdeHgz6niTujUwcLukz8LjLRYXzN++2SlCDQFsrrlWz+l6rSBwYIFPmM5w1soB9xigoqV6F9bQEhnIMB/r5eApwrF3EonS9D9byedNcLeEwTrvXLtOVEQSHK6Zm/QzDqYw8PclW168My7+uULnttb2BOl9KRjz0P4u1nIsuNwYKzLDtXa9+Rn65LAOerJw01TPVTu1jQDxFa+YakaBasrveBwFQcK6NLeUCT79oOB5VMW6ID/bX5dzsC95bbVVlLfNxlGGBgfja7gg8Z2s8sDx91SgmvfAGDm4GSddOGbAEJpU5XJ7BmbBYCPJaZArIPbkXogbJbSnM45xp9BEwf/pC9N2SKDK6RnoaU8Cp+2tQDWvijKZ7o41YbClEVU3AEA2PeXKFgQPeTa3OC1Z+uvF/hAr4gkE8WGm6CGIDFtmBrBlO6e3tGtpHOpHfUzuHWai3CbxKFnQ8EHB09NZljUmAi5YjceFnLROlfSInvmzLGn97pA2GGfQuToEknEGtBEZaNmBrWmUwhAIokRoD7yIGHP2QQDZvdq8IcS9OOiFM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
