travis:
  secure:
    BINSTAR_TOKEN: lqXxWmB89G4gKg8pTyR3smLdZfv9+Ecamg2RYRdltdoGeMRrhLrZfExO1SM1xpVO0K8XX2dlvbFCmY10Z5wDTPfS6hSfJV9fNSfYPJrz/1B4wSInsm8fWFMSnrTrVU1je5wk9xFnxOkSf0Fqw0KmNgX+ubN3VJjBday7g/xREtPqYIWQG9nnihKcOhFJ0t338p4mofLjhD1ChRKFzE+qD+QfVouPeFUXXEPse9wLB8zPJ82qAGDmwKjTGMktATf5k3DUlnC6+7sOIDl+rerRNMeOnZsjEAzQlXKYm2ggWgHyK5XU368SB2LdnIZvcT0TUzID1P/PV8PyNfHFDw6Ly4Fe+i+SNmxENaFj7wIA7E5CrVd2RxO0IlzxS5fPgrdAWA+sN/+RcttNpb+9Tvl91tlI4JeMSx9H7A0WpEl5GzZqLzc6224IdtszdnSGkmDyl39+ve5KGPM6fx70GGq9Q8YucmXJBmkBYJ5lh62Nf2TJO0uUUV+C5Bo2WNWQv/DfnNq+Zs3ZfoMjmfCiUpLACWa00UBksG/mrafsD0RU5ezRp76Uyq2RfhfGWih70RbReWFK2O0R241mRtVyI7wxzcauu7Jbjm+ubVEJwTYooTsgophe2z98Gdoc1n6hkOXL+AdW9Q8yy/vPPBKAoDTIdyE7duGy5APU3QBFRF2Fm+E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
